image:
  file: gitpod.Dockerfile

ports:
  # jupyter notebooks
  - port: 8888
    onOpen: ignore
  # VNC
  - port: 6080
    onOpen: ignore

tasks:
  - name: Startup
    command: ./startup.sh

workspaceLocation: "/workspace"
