image:
  file: gitpod.Dockerfile

ports:
  # jupyter notebooks
  - port: 8888
    onOpen: ignore
  # VNC
  - port: 6080
    onOpen: ignore
  - port: 1024
    onOpen: ignore
  - port: 5900
    onOpen: ignore

tasks:
  - name: Initialization
    command: /workspace/gitpod-vnc/jupyter.sh
  - name: Terminal
    command: /workspace/gitpod-vnc/init.sh
  - name: Test
    command: Hello BioDynaMo

workspaceLocation: "/workspace"
